options {
    STATIC = false;
}

PARSER_BEGIN(Adder)
import java.io.*;
public class Adder {
    public static void main(String[] args) {
        for (String arg : args) {
            try {
                System.out.println(evaluate(arg));
            } catch (ParseException ex) {
                System.err.println(ex.getMessage());
            }
        }
    }

    public static String evaluate(String src) throws ParseException {
        Reader reader = new StringReader(src);
        return new Adder(reader).concatExpr();
    }
}
PARSER_END(Adder)

SKIP: { <[" ", "\t", "\r", "\n"]> }

TOKEN: {
    <STRING_LITERAL: "\"" (~["\""])* "\""> | // 字符串字面量
    <IDENTIFIER: (["a"-"z", "A"-"Z"])+>      // 标识符或变量名
}

String concatExpr():
{
    Token x, y;
}
{
    x=<IDENTIFIER> "+" y=<IDENTIFIER> <EOF>
    {
        return x.image + y.image;
    }
}