server:
  port: 8999

# 百炼平台
langchain4j:
  community:
    dashscope:
      chat-model:
        api-key: ${DASH_SCOPE_API_KEY}
#        model-name: qwen-plus-latest
        model-name: qwen-plus
#        model-name: qwen-turbo-1101
  open-ai:
    chat-model:
      # ==硅基流动==
      base-url: https://api.siliconflow.cn/v1
      api-key: ${GJLD_API_KEY}
      # 免费
#      model-name: deepseek-ai/DeepSeek-R1-0528-Qwen3-8B
#      model-name: Qwen/Qwen3-8B
      # 智谱ai，速度还不错，比上面两个快 【Tools、推理模型】
      model-name: THUDM/GLM-Z1-9B-0414
#      model-name: Qwen/Qwen2.5-7B-Instruct
      # 付费
#      model-name: deepseek-ai/DeepSeek-R1
      # ==kimi==
#      base-url: https://api.moonshot.cn/v1
#      api-key: ${MOONSHOT_API_KEY}
#      model-name: moonshot-v1-8k
#      model-name: kimi-thinking-preview