server:
  port: 8080

langchain4j:
  community:
    dashscope:
      chat-model:
        api-key: ${DASH_SCOPE_API_KEY}
        #        model-name: qwen-plus
        #        model-name: qwen-plus-latest
        model-name: qwen-plus
        #        model-name: qwen-turbo-1101
        # deepseek
      #        model-name: deepseek-r1
      #        model-name: deepseek-v3
      embedding-model:
        api-key: ${DASH_SCOPE_API_KEY}
        model-name: text-embedding-v3