server:
  port: 8999

langchain4j:
  community:
    dashscope:
      chat-model:
        api-key: ${DASH_SCOPE_API_KEY}
        #        model-name: qwen-plus
        #        model-name: qwen-plus-latest
        model-name: qwen-plus
        #        model-name: qwen-turbo-1101
        # deepseek
      #        model-name: deepseek-r1
      #        model-name: deepseek-v3
      embedding-model:
        api-key: ${DASH_SCOPE_API_KEY}
        model-name: text-embedding-v3
  # 内部自部署模型
  xInference:
    chat-model:
      # ==Xorbits Inference==
      # 非思考模型
      base-url: http://172.16.99.68:9997
      model-name: dt_gptq_qwen_int8
