spring:
  ai:
    mcp:
      client:
        sse:
          connections:
            server1:
              url: http://localhost:8080
#            server2:
#              url: http://otherserver:8081
#              sse-endpoint: /custom-sse