/* Generated By:JavaCC: Do not edit this line. CalculatorConstants.java */
package com.changlu.javacc.learning.Calculator.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface CalculatorConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int NUMBER = 4;
  /** RegularExpression Id. */
  int DIGIT = 5;
  /** RegularExpression Id. */
  int EOL = 6;
  /** RegularExpression Id. */
  int SIN = 7;
  /** RegularExpression Id. */
  int COS = 8;
  /** RegularExpression Id. */
  int TAN = 9;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "<NUMBER>",
    "<DIGIT>",
    "\"\\n\"",
    "\"sin\"",
    "\"cos\"",
    "\"tan\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"!\"",
    "\"(\"",
    "\")\"",
  };

}
