# Using spring-ai-starter-mcp-server-webmvc
spring:
  application:
    name: mcp-server
  main:
    web-application-type: reactive
    banner-mode: off
  ai:
    mcp:
      server:
        name: mcp-server-sse
        version: 1.0.0
        type: ASYNC
        stdio: false
        sse: true
        sse-endpoint: /sse
        capabilities:
          tool: true
          resource: true
          prompt: true
          completion: true
server:
  port: 8080